// Code generated by protoc-gen-go. DO NOT EDIT.
// source: download-progress.proto

package download_progress

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatReply_Status int32

const (
	StatReply_NOT_STARTED StatReply_Status = 0
	StatReply_PENDING     StatReply_Status = 1
	StatReply_ACTIVE      StatReply_Status = 2
	StatReply_DONE        StatReply_Status = 3
	StatReply_FAILED      StatReply_Status = 4
)

var StatReply_Status_name = map[int32]string{
	0: "NOT_STARTED",
	1: "PENDING",
	2: "ACTIVE",
	3: "DONE",
	4: "FAILED",
}

var StatReply_Status_value = map[string]int32{
	"NOT_STARTED": 0,
	"PENDING":     1,
	"ACTIVE":      2,
	"DONE":        3,
	"FAILED":      4,
}

func (x StatReply_Status) String() string {
	return proto.EnumName(StatReply_Status_name, int32(x))
}

func (StatReply_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_39caaecc443727ea, []int{1, 0}
}

// Stat request message
type StatRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatRequest) Reset()         { *m = StatRequest{} }
func (m *StatRequest) String() string { return proto.CompactTextString(m) }
func (*StatRequest) ProtoMessage()    {}
func (*StatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_39caaecc443727ea, []int{0}
}

func (m *StatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatRequest.Unmarshal(m, b)
}
func (m *StatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatRequest.Marshal(b, m, deterministic)
}
func (m *StatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatRequest.Merge(m, src)
}
func (m *StatRequest) XXX_Size() int {
	return xxx_messageInfo_StatRequest.Size(m)
}
func (m *StatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatRequest proto.InternalMessageInfo

// Stat response message
type StatReply struct {
	Status               StatReply_Status `protobuf:"varint,1,opt,name=status,proto3,enum=StatReply_Status" json:"status,omitempty"`
	Downloaded           int64            `protobuf:"varint,2,opt,name=downloaded,proto3" json:"downloaded,omitempty"`
	Rate                 int64            `protobuf:"varint,3,opt,name=rate,proto3" json:"rate,omitempty"`
	Length               int64            `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *StatReply) Reset()         { *m = StatReply{} }
func (m *StatReply) String() string { return proto.CompactTextString(m) }
func (*StatReply) ProtoMessage()    {}
func (*StatReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_39caaecc443727ea, []int{1}
}

func (m *StatReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatReply.Unmarshal(m, b)
}
func (m *StatReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatReply.Marshal(b, m, deterministic)
}
func (m *StatReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatReply.Merge(m, src)
}
func (m *StatReply) XXX_Size() int {
	return xxx_messageInfo_StatReply.Size(m)
}
func (m *StatReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StatReply.DiscardUnknown(m)
}

var xxx_messageInfo_StatReply proto.InternalMessageInfo

func (m *StatReply) GetStatus() StatReply_Status {
	if m != nil {
		return m.Status
	}
	return StatReply_NOT_STARTED
}

func (m *StatReply) GetDownloaded() int64 {
	if m != nil {
		return m.Downloaded
	}
	return 0
}

func (m *StatReply) GetRate() int64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *StatReply) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func init() {
	proto.RegisterEnum("StatReply_Status", StatReply_Status_name, StatReply_Status_value)
	proto.RegisterType((*StatRequest)(nil), "StatRequest")
	proto.RegisterType((*StatReply)(nil), "StatReply")
}

func init() { proto.RegisterFile("download-progress.proto", fileDescriptor_39caaecc443727ea) }

var fileDescriptor_39caaecc443727ea = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xbb, 0x6d, 0x88, 0x3a, 0xf5, 0xcf, 0x3a, 0x07, 0x0d, 0x1e, 0xa4, 0xe4, 0x54, 0x85,
	0xa6, 0x52, 0x2f, 0xa2, 0xa7, 0x6a, 0xa2, 0x06, 0x24, 0x2d, 0x49, 0xf0, 0xe0, 0xa5, 0x24, 0x66,
	0x49, 0x0b, 0x69, 0x37, 0xee, 0x6e, 0x28, 0x7e, 0x47, 0x3f, 0x94, 0x24, 0x4d, 0xb4, 0x20, 0x78,
	0x9b, 0xf7, 0x9b, 0xc7, 0xdb, 0x7d, 0xbb, 0x70, 0x9a, 0xf0, 0xf5, 0x2a, 0xe3, 0x51, 0x32, 0xc8,
	0x05, 0x4f, 0x05, 0x93, 0xd2, 0xca, 0x05, 0x57, 0xdc, 0x3c, 0x80, 0x6e, 0xa0, 0x22, 0xe5, 0xb3,
	0x8f, 0x82, 0x49, 0x65, 0x7e, 0x11, 0xd8, 0xdb, 0xe8, 0x3c, 0xfb, 0xc4, 0x0b, 0xd0, 0xa5, 0x8a,
	0x54, 0x21, 0x0d, 0xd2, 0x23, 0xfd, 0xc3, 0xd1, 0xb1, 0xf5, 0xb3, 0xab, 0xa6, 0x42, 0xfa, 0xb5,
	0x01, 0xcf, 0x01, 0x9a, 0x23, 0x58, 0x62, 0xb4, 0x7b, 0xa4, 0xdf, 0xf1, 0xb7, 0x08, 0x22, 0x68,
	0x22, 0x52, 0xcc, 0xe8, 0x54, 0x9b, 0x6a, 0xc6, 0x13, 0xd0, 0x33, 0xb6, 0x4a, 0xd5, 0xdc, 0xd0,
	0x2a, 0x5a, 0x2b, 0xf3, 0x19, 0xf4, 0x4d, 0x3a, 0x1e, 0x41, 0xd7, 0x9b, 0x84, 0xb3, 0x20, 0x1c,
	0xfb, 0xa1, 0x63, 0xd3, 0x16, 0x76, 0x61, 0x67, 0xea, 0x78, 0xb6, 0xeb, 0x3d, 0x51, 0x82, 0x00,
	0xfa, 0xf8, 0x21, 0x74, 0x5f, 0x1d, 0xda, 0xc6, 0x5d, 0xd0, 0xec, 0x89, 0xe7, 0xd0, 0x4e, 0x49,
	0x1f, 0xc7, 0xee, 0x8b, 0x63, 0x53, 0x6d, 0x14, 0x03, 0xb5, 0xeb, 0x3b, 0x4c, 0xeb, 0xde, 0x68,
	0x82, 0x56, 0xa6, 0xe3, 0xbe, 0xb5, 0x55, 0xfc, 0x0c, 0x7e, 0xab, 0x99, 0x2d, 0xbc, 0x04, 0x28,
	0x65, 0xa0, 0x04, 0x8b, 0x96, 0xff, 0x39, 0xaf, 0xc8, 0xfd, 0xed, 0xdb, 0x4d, 0xba, 0x50, 0xf3,
	0x22, 0xb6, 0xde, 0xf9, 0x72, 0xb8, 0x66, 0xb1, 0xe2, 0x62, 0xb0, 0xe0, 0xc3, 0x3f, 0x2f, 0x7e,
	0xd7, 0x90, 0x59, 0x43, 0x62, 0xbd, 0xfa, 0x84, 0xeb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x29,
	0x7b, 0x74, 0x96, 0x9f, 0x01, 0x00, 0x00,
}
